### ISSUE TITLE
Parse range error

### ISSUE THREAD

**Issue by IWANABETHATGUY** [HerringtonDarkholme/vue-template-compiler#10]
vue SFC file
```vue
<template v-if>
  <div v-for="item in result">test {{item}}</div>
</template>
```
```bash
Root 0..78
  Element 0..77
    tag_name `template`
    directive 10..14
      name `if`
    Element 18..65
      tag_name `div`
      directive 23..45
        name `for`
        value 29..45 `item in result`
      Text 51..59 `test `
      Interpolation 51..59 `item`
```
here text `test` byte offset is 51..59, which is wrong,
the correct offset should be `46..51`
![image](https://user-images.githubusercontent.com/17974631/134298265-6260d4c2-c22b-4854-bf6a-3299688235b4.png)

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/HerringtonDarkholme/vue-template-compiler/commit/21c383fdf0a06ce9705a96bd7c490d28958c5a85
